web/pom.xml, web/src/main/java/fr/abes/qualimarc/QualimarcAPIApplication.java
Repackaging en .jar
Ajout mainClass dans pom
=> ODS-116 : Refactor

core/pom.xml, core/src/main/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/Rule.java, core/src/main/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/structure/NombreZone.java, core/src/main/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/structure/PresenceSousZone.java, core/src/main/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/structure/PresenceZone.java, core/src/main/java/fr/abes/qualimarc/core/utils/Operateur.java, core/src/test/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/structure/NombreZoneTest.java
Ajout méthode isValid correspondante
Ajout TU de la méthode
Ajout contraintes NotNull sur les champs de la BDD
=> ODS-113 : Feat : ajout classe NombreZone

core/pom.xml, web/pom.xml, web/src/main/java/fr/abes/qualimarc/web/controller/AbstractController.java, web/src/main/java/fr/abes/qualimarc/web/controller/PublicController.java, web/src/main/java/fr/abes/qualimarc/web/dto/ControllingPpnWithRuleSetsRequestDto.java, web/src/test/java/fr/abes/qualimarc/web/controller/PublicControllerTest.java
ODS-123 : feat
Modification de la classe ControllingPpnWithRuleSetsRequestDto.java
Modification de la classe PublicController.java
Modification de la classe PublicControllerTest.java
=> Ods 123 back ajouter le tu du ws permettant de lancer le traitement

core/src/main/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/structure/NombreSousZones.java, core/src/test/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/structure/NombreSousZonesTest.java, core/src/test/resources/143519379.xml
Ajout code méthode isValid
Ajout TU correspondant
=> ODS-114 : FEAT : Ajout classe NombreSousZones

web/src/main/java/fr/abes/qualimarc/QualimarcAPIApplication.java, web/src/main/resources/application-dev.properties
Ajout des règles au démarrage uniquement en localhost
=> Fix : Initialisation bdd dev en update

core/src/main/java/fr/abes/qualimarc/core/model/resultats/ResultRules.java, core/src/main/java/fr/abes/qualimarc/core/service/ReferenceService.java, core/src/main/java/fr/abes/qualimarc/core/service/RuleService.java, core/src/test/java/fr/abes/qualimarc/core/service/RuleServiceTest.java, web/src/main/java/fr/abes/qualimarc/web/dto/ResultRulesResponseDto.java, web/src/main/java/fr/abes/qualimarc/web/mapper/WebDtoMapper.java, web/src/test/java/fr/abes/qualimarc/web/mapper/WebDtoMapperTest.java
- ajouter la famille de document dans le retour du WS d'analyse de ppn
- modifier la liste de ppn pour ne retourner que ceux présentant des erreurs
- modification des TU en conséquence
=> ODS-170 : feat

core/src/main/java/fr/abes/qualimarc/core/model/entity/notice/NoticeXml.java, core/src/main/java/fr/abes/qualimarc/core/model/resultats/ResultRules.java, core/src/main/java/fr/abes/qualimarc/core/service/RuleService.java, core/src/test/java/fr/abes/qualimarc/core/model/entity/basexml/NoticeXmlTest.java, core/src/test/java/fr/abes/qualimarc/core/service/RuleServiceTest.java, core/src/test/resources/checkRules1.xml, web/src/main/java/fr/abes/qualimarc/QualimarcAPIApplication.java, web/src/main/java/fr/abes/qualimarc/web/dto/ResultRulesResponseDto.java, web/src/main/java/fr/abes/qualimarc/web/mapper/WebDtoMapper.java, web/src/test/java/fr/abes/qualimarc/web/mapper/WebDtoMapperTest.java
- Ajout méthode récupération ocn dans notice
- Ajout ocn dans objet métier
- modification couche service pour ajout de l'ocn dans l'objet métier
- ajout ocn dans réponse webdto
- modification mapper objet métier -> réponse webdto
- ajustement des TU
=> ODS-184 : ajout OCN dans retour ws

core/src/main/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/structure/PositionSousZone.java, core/src/test/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/structure/PositionSousZoneTest.java, web/src/main/java/fr/abes/qualimarc/web/controller/RuleController.java, web/src/main/java/fr/abes/qualimarc/web/dto/indexrules/PositionSousZoneWebDto.java, web/src/main/java/fr/abes/qualimarc/web/dto/indexrules/RulesWebDto.java, web/src/main/java/fr/abes/qualimarc/web/mapper/WebDtoMapper.java, web/src/test/java/fr/abes/qualimarc/web/mapper/WebDtoMapperTest.java
Ajout entité
Ajout codage méthode isValid
Ajout WebDto pour indexation de la règle
Modification des mappers
prise en compte du nouveau type de règle dans les Dto en entrée du controller Ajouts TU
=> ODS-135 : Ajout règle PositionSousZone :

web/src/main/resources/import.sql
- modification de la liste des jeux de règles injecté dans la BDD
=> ODS-222 : modif du importSQL

core/src/main/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/contenu/chainecaracteres/ChaineCaracteres.java, core/src/test/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/contenu/PresenceChaineCaracteresTest.java, web/src/main/java/fr/abes/qualimarc/web/mapper/WebDtoMapper.java
- correction des constructeurs de l'entité ChaineCaracteres.java
- adaptation des TU
- adaptation du mapper (méthode constructPresenceChaineCaracteres() )
=> ODS-280 : hot-fix

core/src/main/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/contenu/PresenceChaineCaracteres.java, core/src/main/java/fr/abes/qualimarc/core/utils/EnumTypeVerification.java, core/src/test/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/contenu/PresenceChaineCaracteresTest.java, core/src/test/resources/143519379.xml
. fix du bug sur la détection sur plusieurs occurrences de zones et sous-zones
. ajout du type de recherche NECONTIENTPAS
=> Fix strictement sur plusieurs occurences

web/src/main/java/fr/abes/qualimarc/web/dto/reference/FamilleDocumentWebDto.java
j'avais oublié de modifier la familleDoc dto
=> Fix Selection FamilleDocumentWebDto

core/src/test/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/contenu/PresenceChaineCaracteresTest.java, core/src/test/resources/143519379.xml
- correction du bug sur la notice de test
- adaptation des TU de l'entité PresenceChaineCaracteresTest.java
=> FIX bug sur les TU

web/src/main/java/fr/abes/qualimarc/web/dto/indexrules/contenu/PresenceChaineCaracteresWebDto.java
ajout regex NECONTIENTPAS dans pattern
=> ODS-303-bug resolution bug

web/src/main/java/fr/abes/qualimarc/web/mapper/WebDtoMapper.java
- ajout de l'Enum NECONTIENTPAS dans la méthode getTypeVerification() de la classe WebDtoMapper.java
=> FIX : bug ajout NECONTIENTPAS en bdd

core/src/main/java/fr/abes/qualimarc/core/service/RuleService.java, web/src/main/java/fr/abes/qualimarc/web/controller/RuleController.java, web/src/main/java/fr/abes/qualimarc/web/dto/RuleWebDto.java, web/src/main/java/fr/abes/qualimarc/web/mapper/WebDtoMapper.java, web/src/test/java/fr/abes/qualimarc/web/mapper/WebDtoMapperTest.java
- Ajout Controller
- Ajout méthode dans couche service
- Ajout Webdto & mapper
- Ajout TU mapper
=> ODS-309 : ajout ws récupération de la liste des règles

web/src/main/java/fr/abes/qualimarc/web/configuration/WebConfig.java, web/src/main/java/fr/abes/qualimarc/web/controller/RuleController.java, web/src/main/java/fr/abes/qualimarc/web/dto/indexrules/DependencyWebDto.java, web/src/main/java/fr/abes/qualimarc/web/dto/indexrules/SimpleRuleWebDto.java, web/src/main/java/fr/abes/qualimarc/web/mapper/WebDtoMapper.java, web/src/test/java/fr/abes/qualimarc/web/controller/RuleControllerTest.java, web/src/test/java/fr/abes/qualimarc/web/mapper/WebDtoMapperTest.java
- Ajout webdto
- Modification du mapper
- Ajout d'un TU dans le controller pour vérifier qu'on ne peut pas créer une règle simple de type dépendance
- TU du mapper avec prise en compte de toutes les règles de gestion
=> ODS-333 : Ajout création de règles de dépendances

core/src/main/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/contenu/ComparaisonContenuSousZone.java, core/src/test/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/contenu/ComparaisonContenuSousZoneTest.java, web/src/test/java/fr/abes/qualimarc/web/mapper/WebDtoMapperTest.java
- correction d'un bug sur le type de vérification TERMINE
- refactor de la méthode isValid()
=> FEAT : ODS-92

core/src/main/java/fr/abes/qualimarc/core/model/resultats/ResultAnalyse.java, core/src/main/java/fr/abes/qualimarc/core/service/RuleService.java, core/src/test/java/fr/abes/qualimarc/core/service/RuleServiceTest.java, core/src/test/resources/noticeSansFamille.xml, web/src/main/java/fr/abes/qualimarc/web/controller/RuleController.java, web/src/main/java/fr/abes/qualimarc/web/mapper/WebDtoMapper.java
=> Fix : Ajout cas dans vérification passage d'une règle sur une notice

core/src/main/java/fr/abes/qualimarc/core/service/RuleService.java, web/src/main/java/fr/abes/qualimarc/web/controller/RuleController.java
- déplacement du nb total de ppn traités vers le controller
=> Fix : correction calcul progression

core/src/main/java/fr/abes/qualimarc/core/model/entity/qualimarc/reference/FamilleDocument.java, core/src/main/java/fr/abes/qualimarc/core/model/entity/qualimarc/reference/RuleSet.java, core/src/main/java/fr/abes/qualimarc/core/repository/qualimarc/FamilleDocumentRepository.java, core/src/main/java/fr/abes/qualimarc/core/service/ReferenceService.java
- ajout d'un implement Comparable et de la méthode compareTo() associée dans RuleSet.java
- ajout d'un tri sur la liste de RuleSet de la méthode getRuleSets() dans ReferenceService.java
=> FEAT : ODS-431

web/src/main/java/fr/abes/qualimarc/web/controller/ReferenceController.java
=> FEAT : ODS-299

batch/src/main/java/fr/abes/qualimarc/batch/webstats/FlushStatistiquesTasklet.java
=> REFACTOR : ODS-509

core/src/main/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/contenu/Indicateur.java, core/src/test/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/ComplexRuleTest.java, core/src/test/java/fr/abes/qualimarc/core/model/entity/qualimarc/rules/contenu/IndicateurTest.java, web/src/main/java/fr/abes/qualimarc/web/controller/RuleController.java, web/src/main/java/fr/abes/qualimarc/web/dto/indexrules/contenu/IndicateurWebDto.java, web/src/main/java/fr/abes/qualimarc/web/mapper/WebDtoMapper.java, web/src/test/java/fr/abes/qualimarc/web/mapper/WebDtoMapperTest.java
- ajout d'un paramètre TypeVerification dans Indicateur.java
- modification de IndicateurTest.java
- ajout d'un paramtètre String typeDeVerification dans IndicateurWebDto.java
- modification de WebDtoMapper.java, WebDtoMapperTest.java, ComplexRuleTest.java et RuleController.java
=> FEAT : ODS-517

docker/batch/tasks.tmpl
- redirection des logs du flush
=> FIX : log redirection

web/src/main/java/fr/abes/qualimarc/web/mapper/WebDtoMapper.java
- correctif apporté dans WebDtoMapper.java
=> FIX : IllegalArgumentException Indicateur

batch/src/main/java/fr/abes/qualimarc/batch/Application.java, batch/src/main/java/fr/abes/qualimarc/batch/BatchConfiguration.java, batch/src/main/java/fr/abes/qualimarc/batch/QualimarcBatchConfigurer.java, batch/src/main/java/fr/abes/qualimarc/batch/TimeIncrementer.java, batch/src/main/java/fr/abes/qualimarc/batch/webstats/VerifierParamsTasklet.java, batch/src/main/resources/application.properties, docker/batch/qualimarc-batch.sh
Utilisation commandLineRunner et récupération des paramètres en ligne de commande pour les injecter dans le job
=> Fix : correction appel batch en ligne de commande

web/src/main/java/fr/abes/qualimarc/web/controller/ReferenceController.java
- modification de la description EXPERTE
=> FIX : correction-label-analyse-experte
